name: Release Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        include:
          - os: ubuntu-latest
            output_name: light-ai-linux
            target: bun-linux-x64-modern
          - os: windows-latest
            output_name: light-ai-win.exe
            target: bun-windows-x64-modern
          - os: macos-latest
            output_name: light-ai-mac-silicon
            target: bun-darwin-arm64
          - os: macos-13
            output_name: light-ai-mac-intel
            target: bun-darwin-x64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build models
        run: bun ./scripts/buildModels.ts

      - name: Build binary
        run: bun build ./src/app.ts --target=${{ matrix.target }} --minify --compile --sourcemap --outfile ${{ matrix.output_name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: ${{ matrix.output_name }}

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get Package Version
        id: package_version
        run: |
          echo VERSION=$(node --print "require('./package.json').version") >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: out
          pattern: light-ai-*
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R out

      - name: Release v${{ env.VERSION }}
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ env.VERSION }}
          body: See the assets to download this version and install.
          files: |
            out/*
          draft: true
          prerelease: false
          generate_release_notes: false
          fail_on_unmatched_files: false
